name: CI/CD for brew site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t oldeesrock/brew-webserver

    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: push the Docker image
      run: docker push oldeesrock/brew-webserver

    - name: check directory
      run: ls
    - name: Upload S3
      # You may pin to the exact commit or the version.
      # uses: shallwefootball/upload-s3-action@bcd7c2408245fd6cd19b5512a473b1a7a8b48a35
      uses: shallwefootball/upload-s3-action@v1.1.3
      with:
        # aws key id
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        # aws secret access key
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
        # aws bucket name
        aws_bucket: ${{ secrets.S3_BUCKET }}
        # directory to upload
        source_dir: ./api/public/data
        # destination directory for upload
        destination_dir: magic-bean-brewing/public/
      
    - name: AWS Elastic Beanstalk cli
      uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: 'deploy ${{ secrets.BREW_SITE_ENVIRONMENT_NAME }}'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: "us-west-2"
