name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build . 
      
    - uses: actions/checkout@v2
    - name: push the Docker image
      run: docker-compose push . 
      
    - name: Build and push Docker images

      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: oldeesrock\magic-bean-brewing:brew-express
